QUnit.testSuites([
    "bndr-core-tests.html",
	"helper-tests.html",
	"bind-list-tests.html",
    "bind-dom-tests.html",
	"bind-attribute-tests.html",
	"bind-class-tests.html",
	"bind-style-tests.html",
	"bind-event-tests.html",
	"bind-change-tests.html",
	"compute-tests.html",
    "bind-toggle-tests.html",
    "bind-drag-tests.html",
    "bind-storage-tests.html"
]);
